# SharePoint Credentials & Configuration
sharepoint:
  user_login: "your-email@your-domain.com"
  user_password: "your_password"
  library_url: "https://your-tenant.sharepoint.com/sites/YourSite/YourLibrary"  # Example: https://your-tenant.sharepoint.com/sites/YourSite/YourLibrary
  source_folder: "Source"      # Name of the folder with new files
  imported_folder: "Imported"  # Name of the folder for successfully processed files
  broken_folder: "Broken"      # Name of the folder for files with errors

# PostgreSQL Database Configuration
database:
  user_login: "test"
  user_password: "test"
  host: "localhost"
  port: 5432
  db_name: "testdb"
  schema: "blacklist"
  table: "entity"

# Local Folders for Phase 1
local:
  input_folder: "data/input" # use: "/data/input" in Unix environment
  imported_folder: "data/imported" # use: "/data/imported" in Unix environment
  broken_folder: "data/broken" # use: "/data/broken" in Unix environment

# Schema API Configuration (for Phase 2)
schema_api:
  url: "https://api.example.com/schemas/descriptive_data"
  user: "api_user"
  password: "api_password"

# Email Notification Configuration
notifications:
  smtp_server_address: "smtp.your-email-provider.com:25"  # address with port, e.g. smtp.domain.com:25
  from: "somerecipient@domain.com"  # default sender address
  sending_email_enabled: false  # if false, do not send emails, just log the content
  subject_prefix: "This is email from system X"  # default subject prefix 