# SharePoint Credentials & Configuration
sharepoint:
  user_login: "your-email@your-domain.com"
  user_password: "your_password"
  library_url: "https://your-tenant.sharepoint.com/sites/YourSite/YourLibrary"

# PostgreSQL Database Configuration
database:
  user_login: "test"
  user_password: "test"
  host: "localhost"
  port: 5432
  db_name: "testdb"
  schema: "blacklist"
  table: "entity"

# Local Folders for Phase 1
local:
  input_folder: "data/input" # use: "/data/input" in Unix environment
  output_folder: "data/output" # use: "/data/output" in Unix environment
  imported_folder: "data/imported" # use: "/data/imported" in Unix environment
  broken_folder: "data/broken" # use: "/data/broken" in Unix environment

# Schema API Configuration (for Phase 2)
schema_api:
  url: "https://api.example.com/schemas/descriptive_data"
  user: "api_user"
  password: "api_password"

# Email Notification Configuration
notifications:
  smtp_server: "smtp.your-email-provider.com"
  smtp_port: 587
  smtp_user: "your-email@your-domain.com"
  smtp_password: "your_password"
  sender_email: "noreply@your-domain.com" 